export enum AlertType {
  ACCIDENT = "ACCIDENT",
  JAM = "JAM",
  WEATHERHAZARD = "WEATHER_HAZARD",
  MISC = "MISC",
  CONSTRUCTION = "CONSTRUCTION",
  ROAD_CLOSED = "ROAD_CLOSED",
  HAZARD = "HAZARD",
}

export enum AlertSubType {
  // ACCIDENT
  ACCIDENT_MINOR = "ACCIDENT_MINOR",
  ACCIDENT_MAJOR = "ACCIDENT_MAJOR",
  ACCIDENT_NO_SUBTYPE = "ACCIDENT_NO_SUBTYPE",

  // JAM
  JAM_MODERATE_TRAFFIC = "JAM_MODERATE_TRAFFIC",
  JAM_HEAVY_TRAFFIC = "JAM_HEAVY_TRAFFIC",
  JAM_STAND_STILL_TRAFFIC = "JAM_STAND_STILL_TRAFFIC",
  JAM_LIGHT_TRAFFIC = "JAM_LIGHT_TRAFFIC",
  JAM_NO_SUBTYPE = "JAM_NO_SUBTYPE",

  // HAZARD / WEATHER
  HAZARD_ON_ROAD = "HAZARD_ON_ROAD",
  HAZARD_ON_SHOULDER = "HAZARD_ON_SHOULDER",
  HAZARD_WEATHER = "HAZARD_WEATHER",
  HAZARD_ON_ROAD_OBJECT = "HAZARD_ON_ROAD_OBJECT",
  HAZARD_ON_ROAD_POT_HOLE = "HAZARD_ON_ROAD_POT_HOLE",
  HAZARD_ON_ROAD_ROAD_KILL = "HAZARD_ON_ROAD_ROAD_KILL",
  HAZARD_ON_SHOULDER_CAR_STOPPED = "HAZARD_ON_SHOULDER_CAR_STOPPED",
  HAZARD_ON_SHOULDER_ANIMALS = "HAZARD_ON_SHOULDER_ANIMALS",
  HAZARD_ON_SHOULDER_MISSING_SIGN = "HAZARD_ON_SHOULDER_MISSING_SIGN",
  HAZARD_WEATHER_FOG = "HAZARD_WEATHER_FOG",
  HAZARD_WEATHER_HAIL = "HAZARD_WEATHER_HAIL",
  HAZARD_WEATHER_HEAVY_RAIN = "HAZARD_WEATHER_HEAVY_RAIN",
  HAZARD_WEATHER_HEAVY_SNOW = "HAZARD_WEATHER_HEAVY_SNOW",
  HAZARD_WEATHER_FLOOD = "HAZARD_WEATHER_FLOOD",
  HAZARD_WEATHER_MONSOON = "HAZARD_WEATHER_MONSOON",
  HAZARD_WEATHER_TORNADO = "HAZARD_WEATHER_TORNADO",
  HAZARD_WEATHER_HEAT_WAVE = "HAZARD_WEATHER_HEAT_WAVE",
  HAZARD_WEATHER_HURRICANE = "HAZARD_WEATHER_HURRICANE",
  HAZARD_WEATHER_FREEZING_RAIN = "HAZARD_WEATHER_FREEZING_RAIN",
  HAZARD_ON_ROAD_LANE_CLOSED = "HAZARD_ON_ROAD_LANE_CLOSED",
  HAZARD_ON_ROAD_OIL = "HAZARD_ON_ROAD_OIL",
  HAZARD_ON_ROAD_ICE = "HAZARD_ON_ROAD_ICE",
  HAZARD_ON_ROAD_CONSTRUCTION = "HAZARD_ON_ROAD_CONSTRUCTION",
  HAZARD_ON_ROAD_CAR_STOPPED = "HAZARD_ON_ROAD_CAR_STOPPED",
  HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT = "HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT",
  HAZARD_NO_SUBTYPE = "HAZARD_NO_SUBTYPE",

  // MISC
  MISC_NO_SUBTYPE = "MISC_NO_SUBTYPE",

  // CONSTRUCTION
  CONSTRUCTION_NO_SUBTYPE = "CONSTRUCTION_NO_SUBTYPE",

  // ROAD_CLOSED
  ROAD_CLOSED_HAZARD = "ROAD_CLOSED_HAZARD",
  ROAD_CLOSED_CONSTRUCTION = "ROAD_CLOSED_CONSTRUCTION",
  ROAD_CLOSED_EVENT = "ROAD_CLOSED_EVENT",
  ROAD_CLOSED_NO_SUBTYPE = "ROAD_CLOSED_NO_SUBTYPE",
}
